import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { i18n } from "../../i18n-config";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
	title: "Sklep",
	description: "Generated by create next app",
};

console.log(metadata);
export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: string };
}) {
	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<section className="sm :max-w-6xl mx-auto max-w-md p-12 sm:max-w-7xl ">{children}</section>
			</body>
		</html>
	);
}
